# trigger: master
trigger: 
- master

pool: default

steps:
- script: ls
  displayName: 'Print Directory Content'
- script: pwd
  displayName: 'Server Directory Location'
- script: env
  displayName: 'Available Env Variables'
- script: chmod 0755 ./ado/do_patch.sh
  displayName: 'Update Permissions'
- script: ./ado/do_patch.sh
  displayName: 'Tag Servers'
